l="""
/fcp-indi/data/Projects/CORR/RawDataBIDS/BMB_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_3
/fcp-indi/data/Projects/CORR/RawDataBIDS/DC_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/HNU_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/IACAS
/fcp-indi/data/Projects/CORR/RawDataBIDS/IBA_TRT
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_3
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_4
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_5
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_6
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_7
/fcp-indi/data/Projects/CORR/RawDataBIDS/IPCAS_8
/fcp-indi/data/Projects/CORR/RawDataBIDS/JHNU
/fcp-indi/data/Projects/CORR/RawDataBIDS/LMU_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/LMU_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/LMU_3
/fcp-indi/data/Projects/CORR/RawDataBIDS/MPG_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/MRN
/fcp-indi/data/Projects/CORR/RawDataBIDS/NKI_TRT
/fcp-indi/data/Projects/CORR/RawDataBIDS/NYU_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/NYU_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/SWU_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/SWU_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/SWU_3
/fcp-indi/data/Projects/CORR/RawDataBIDS/SWU_4
/fcp-indi/data/Projects/CORR/RawDataBIDS/UM
/fcp-indi/data/Projects/CORR/RawDataBIDS/UPSM_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/Utah_1
/fcp-indi/data/Projects/CORR/RawDataBIDS/Utah_2
/fcp-indi/data/Projects/CORR/RawDataBIDS/UWM
/fcp-indi/data/Projects/CORR/RawDataBIDS/XHCUMS
"""


o="\n".join(["duck --verbose --retry -y -e compare --parallel 2 --download s3:/{}/ /data.nfs/CORR/dl".format(i) for i in l.split()])
print(o)
